apiVersion: v1
kind: ServiceAccount
metadata:
  name: bunny-cdn-operator-service-account
  namespace: core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: bunny-cdn-operator-service-cluster-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "delete", "create"]
  - apiGroups: ["bunny-cdn-operator.com"]
    resources:
      ["pullzones", "pullzones/status", "pullzones/finalizers", "storagezones", "storagezones/status", "storagezones/finalizers", "edgerules", "edgerules/status", "edgerules/finalizers"]
    verbs: ["get", "watch", "update", "patch", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: bunnycdn-operator-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: bunny-cdn-operator-service-account
    namespace: core
roleRef:
  kind: ClusterRole
  name: bunny-cdn-operator-service-cluster-role
  apiGroup: rbac.authorization.k8s.io
